- Gemfile
- libraries/helper.rb
- recipes/_common.rb
- recipes/_git.rb
- recipes/_github.rb
- recipes/_openssl.rb
- recipes/_packaging.rb
- recipes/_xml.rb
- recipes/_yaml.rb
This puts some Solaris 11 specific functionality in the omnibus cookbook.
> Update omnibus to function with Solaris 11 natively

- .kitchen.yml
- recipes/_packaging.rb
> Install glibc-static on el6 and later, for use in analytics build.

- recipes/_environment.rb
/cc @scotthain @curiositycasualty
> `gmake` lives in `/usr/sfw/bin` on Solaris 10

- libraries/ruby_install.rb
- recipes/_compile.rb
- recipes/_environment.rb
- recipes/_ruby.rb
- spec/recipes/compile_spec.rb
- spec/recipes/ruby_spec.rb
/cc @scotthain @curiositycasualty
> Solaris 10/11 fixes

- libraries/ruby_install.rb
- recipes/_ruby.rb
- spec/recipes/ruby_spec.rb
/cc @curiositycasualty @scotthain
> Support installing Ruby 2.1.5 on Solaris 11

- recipes/_git.rb
- spec/recipes/git_spec.rb
> Solaris 10 Git config fixes

- libraries/remote_install.rb
- recipes/_fakeroot.rb
- recipes/_libffi.rb
- recipes/_packaging.rb
- recipes/_rsync.rb
- recipes/default.rb
This PR is meant to replace https://github.com/opscode-cookbooks/omnibus/pull/94
/cc @opscode-cookbooks/ociv
> Slight refactor of "Changes to prepare rhel (ppc64/le) and ubuntu(ppc64le) build machines"

- .delivery/build-cookbook/recipes/deploy.rb
- CHANGELOG.md
/cc @cwebberOps 
Will fix the following failure: 
https://delivery.chef.co/e/chef/#/organizations/chef-cookbooks/projects/omnibus/changes/a7fda51c-63d7-4b66-8ad5-08671d305014/status/delivered
> Ensure chef-sugar is loaded before using DataBag helpers

- .delivery/build-cookbook/metadata.rb
- .delivery/build-cookbook/recipes/deploy.rb
- metadata.rb
The default CCR is taking place in the context of Chef Zero.
/cc @cwebberOps @chefsalim
> Properly load data bag item from Chef Server

- .delivery/build-cookbook/recipes/deploy.rb
> Fully qualify the `with_server_config` helper

- .kitchen.yml
- CHANGELOG.md
- attributes/default.rb
- libraries/omnibus_build.rb
- libraries/ruby_install.rb
- metadata.rb
- spec/libraries/omnibus_build_spec.rb
- spec/spec_helper.rb
- test/fixtures/cookbooks/omnibus_build/recipes/execute.rb
/cc @chef-cookbooks/engineering-services @chef-cookbooks/omnibus-maintainers @xenolinguist
> [ES-479] Add Windows support to the `omnibus_build` resource

- attributes/default.rb
- libraries/helper.rb
- recipes/_omnibus_toolchain.rb
- recipes/_user.rb
> Update omnibus toolchain for AIX, enable toolchain shell on AIX

- recipes/_environment.rb
> Add XLC to PATH on AIX

- attributes/default.rb
- libraries/helper.rb
- recipes/_compile.rb
- recipes/_git.rb
- recipes/_omnibus_toolchain.rb
- recipes/_user.rb
See commit messages for full details.
> Various Toolchain and OS X Fixes

- recipes/_user.rb
- spec/recipes/user_spec.rb
> 'build_user_shell' is not longer a node attribute

- recipes/_environment.rb
> Sort env & tool list on all platforms.

- libraries/helper.rb
- recipes/_omnibus_toolchain.rb
- recipes/_user.rb
- recipes/default.rb
> Enable omnibus toolchain for nexus platform

- libraries/helper.rb
- recipes/_omnibus_toolchain.rb
> Enable Omnibus Toolchain for ios_xr

- .rubocop.yml
- attributes/default.rb
- recipes/_packaging.rb
- recipes/_user.rb
- spec/recipes/cacerts_spec.rb
- spec/recipes/compile_spec.rb
- spec/recipes/git_spec.rb
- spec/recipes/openssl_spec.rb
- spec/recipes/packaging_spec.rb
> Make Travis pass again

- recipes/_common.rb
- recipes/_packaging.rb
> Update for seven_zip install

- recipes/_environment.rb
> Update load-omnibus-toolchain to reflect correct gcc on freebsd9

- recipes/_compile.rb
- spec/recipes/compile_spec.rb
@chef-cookbooks/engineering-services @chef-cookbooks/omnibus-maintainers
> Fix accidental removal of bzip2 on RHEL

- recipes/_environment.rb
I think delivery ate #119 months ago and this is a revived copy of the same pr. Fixes #101
> add environment variables to powershell profile

- .travis.yml
> Begin linting with CookStyle

- metadata.rb
- recipes/_compile.rb
- recipes/_user.rb
- spec/recipes/compile_spec.rb
Needs https://github.com/chef-cookbooks/build-essential/pull/111 and https://github.com/chef-cookbooks/mingw/pull/6
> Export msys2 based environment on windows

- attributes/default.rb
- recipes/_omnibus_toolchain.rb
- spec/recipes/omnibus-toolchain_spec.rb
Is this the correct ruby idiom? (the to_sym I mean?)
> Allow toolchain channel override

- attributes/default.rb
@chef-cookbooks/engineering-services @chef-cookbooks/omnibus-maintainers
> Bump toolchain version

- attributes/default.rb
> Update omnibus-toolchain version

- Rakefile
- libraries/omnibus_build.rb
- recipes/_common.rb
- spec/libraries/provider_omnibus_build_spec.rb
- test/integration/default/serverspec/default_spec.rb
> Cookstyle fixes

- attributes/default.rb
Promoted omnibus-toolchain 1.1.52 to stable.
> Update omnibus-toolchain to version 1.1.52

- CHANGELOG.md
- metadata.rb
- Update omnibus-toolchain to version 1.1.52
- Switching to stable chef release
> Release v5.1.2

- attributes/default.rb
- spec/recipes/cacerts_spec.rb
- spec/recipes/compile_spec.rb
- spec/recipes/packaging_spec.rb
> Update toolchain version

- attributes/default.rb
Use the newest and bestest! (And not broken-ist!)
> Bump toolchain v1.1.64

- recipes/_omnibus_toolchain.rb
- spec/recipes/omnibus_toolchain_spec.rb
> Install omnibus toolchain correctly based upon system architecture

- metadata.rb
- recipes/_compile.rb
This is a Foodcritic warning now
> Fix node.set for Chef 14

- .kitchen.yml
- .travis.yml
- spec/libraries/provider_omnibus_build_spec.rb
- spec/libraries/resource_omnibus_build_spec.rb
- spec/recipes/compile_spec.rb
- spec/recipes/packaging_spec.rb
Use non-deprecated mocks.
Signed-off-by: Tim Smith <tsmith@chef.io>
> Update Fauxhai mocks in Chefspec

- recipes/_selinux.rb
> Include sbins in path for for selinux calls

- .travis.yml
- README.md
- attributes/default.rb
- metadata.rb
- recipes/_libffi.rb
> Make pkg-config compiletime

- attributes/default.rb
This pulls in the windows fixes required to build anything.
> Updated toolchain for windows fixes

- attributes/default.rb
> Bump toolchain to include users fix and git pack fix

- .kitchen.yml
- attributes/default.rb
- Update toolchain to latest released version (always pull latest from stable)
- Update kitchen yml
- Remove very old unused attributes
> Clean up and update

- .kitchen.dokken.yml
- .kitchen.yml
- .travis.yml
- libraries/matchers.rb
- recipes/_compile.rb
- recipes/_packaging.rb
We require mildly modern Chef so lets use some newer functionality
> Use newer / better Chef functionality

- recipes/_omnibus_toolchain.rb
> We have native sles packages now for toolchain, let's use them

- attributes/default.rb
> Pin toolchain to older version to mitigate windows patch.exe issue

- attributes/default.rb
This will pull the latest stable toolchain (1.1.90) as of this commit which resolves the windows error 127
This will pull the latest stable toolchain (1.1.90) as of this commit which resolves the windows error 127
> Get latest stable toolchain

- recipes/_environment.rb
Updates the xlC PATH to include latest fixpack for AIX 7.1
> Update version for AIX xlC path
