chef-cookbooks/omnibus

libraries/ruby_install.rb

This can wreck absolute havoc in your chef-client runs (CCR) if it install gems into Chef’s Ruby environment (via chef_gem).
/cc @opscode-cookbooks/ociv

Ruby install should not modify the PATH on Win systems

---

libraries/ruby_install.rb

This can cause issues in the CCR when Chef’s underlying `ssl_verify_mode` config option is set to `:verify_peer` which is the default for Chef 12+.
/cc @opscode-cookbooks/ociv @jdmundrawala @adamedx

Don’t configure `SSL_CERT_FILE` globally on Windows

---

recipes/_packaging.rb

Adding to this branch as we run across changes needed to build omnibus packages on el7:
* Package signing on EL7 requires the rpm-sign package.
cc @opscode-cookbooks/ociv @mattray @kaustubh-d

EL 7 build requirements

---

libraries/ruby_install.rb

See the following for more info:
https://github.com/opscode/chef-dk/issues/199
https://blog.mozilla.org/security/2014/09/08/phasing-out-certificates-with-1024-bit-rsa-keys/
https://forums.aws.amazon.com/thread.jspa?threadID=164095
https://github.com/opscode/omnibus-supermarket/commit/89197026af2931de82cfdc13d92ca2230cced3b6
/cc @opscode-cookbooks/ociv

[ruby-windows] install a cacerts bundle that works with the S3 root cert

---

recipes/_ccache.rb
recipes/_rsync.rb
spec/recipes/ccache_spec.rb
spec/recipes/rsync_spec.rb

Reverts 4fc349c.  We already use the samba mirror for rsync in omnibus-software, and the currently specified mirror doesn't seem to be consistently more stable.
cc @opscode-cookbooks/ociv

Use samba mirror for ccache and rsync packages

---

recipes/_packaging.rb

This is a workaround for a bug in either the 7-zip installer or the
cookbook.
Apparently 7-zip isn't respecting the install path on the command line,
and is installing itself to Program Files instead. But we set the path
to the directory we think it should be going in. Leaving the old
command in place just incase something fixes itself upstream.

Add path for 7-zip

---

recipes/_packaging.rb

@mattray @kaustubh-d Let me know if I've accurately reflected what needs to happen on Power.
@sersut @josephrdsmith This should get the analytics build past the libhugetlbfs break. (Tested manually here:  http://wilson.ci.chef.co/job/opscode-analytics-build/1398/architecture=x86_64,platform=el-7,project=opscode-analytics,role=builder/console)
cc @opscode-cookbooks/ociv

Install glibc-static on non-Power platforms running el-6 or higher.

---

recipes/_fakeroot.rb

relative_path was removed in https://github.com/opscode-cookbooks/omnibus/commit/06966905ef716455001b0123fbd0c3ea869fe106
@opscode-cookbooks/engineering-services

Update fakeroot recipe to remove obsolete element

---

libraries/helper.rb

This causes chefspec failures in certain situations

File::ALT_SEPARATOR isn't always a string

---

.kitchen.yml
recipes/_bash.rb
recipes/_git.rb
recipes/_rsync.rb
recipes/_user.rb
spec/recipes/bash_spec.rb
spec/recipes/rsync_spec.rb

cc @opscode-cookbooks/engineering-services
Most of these changes are to accommodate OS X 10.11 System Image Protection, which does not allow modifications to `/usr/bin`.

Support OS X 10.11

---

recipes/_ruby.rb

Fedora has the same issue with bzip in a base install. This uses the Chef DSL to check the platform for RHEL and Fedora, rather than copy pasta the same code block for Fedora.
Resolves #115

Use Chef DSL for Ruby install on RHEL and Fedora

---

.delivery/config.json
metadata.rb

This will ensure the `omnibus` cookbook is available in URD deployments following the automatic environment pinning updates.
/cc @yzl @oferrigni

Publish updates to the chef-server.delivery.chef.co

---

.delivery/config.json

We are already leveraging Delivery’s GitHub integration so no push is needed.

delivery-truck should not push to GitHub

---

CHANGELOG.md
libraries/omnibus_build.rb
libraries/ruby_install.rb
metadata.rb
recipes/_git.rb
spec/libraries/provider_omnibus_build_spec.rb
spec/libraries/provider_omnibus_build_windows_spec.rb
spec/libraries/resource_omnibus_build_spec.rb

Builds on changes introduced in #130. This removes gnarly branching logic for the Windows case. It also allows a multi-line command on *nix so the sourcing of the `load-omnibus-toolchain.sh` works as expected.
/cc @oferrigni @yzl @xenolinguist

[ES-479] Create a separate OmnibusBuild provider for Windows

---

CHANGELOG.md
libraries/omnibus_build.rb
metadata.rb

The `ChefConfig` class is only available on recent versions of Chef.
/cc @chef-cookbooks/delivery-migration-team

Fix Windows detection on older Chef versions

---

.kitchen.wpar.yml

@schisamo - uses an ENV ('AIX_{6,7}1_{L,W}PAR_PASSWORD') to set the desired WPAR/LPAR password for use when connecting to such.

Add wpar yml file

---

recipes/_omnibus_toolchain.rb

This fixes the case where `omnibus-toolchain` will not install on a builder that has built `angry-omnibus-toolchain` one time. It also allows us to support upgrade scenarios.

Properly detect if the Toolchain is installed at a particular version

---

libraries/omnibus_build.rb
spec/libraries/provider_omnibus_build_spec.rb

If you don't have any config_overrides like this:
```ruby
omnibus_build 'foo' do
project_dir '/home/vagrant/foo'
end
```
Will create a command line like this:
```
bundle exec omnibus build foo --log-level internal --config /home/vagrant/foo/omnibus.rb --override
```
Which isn't valid and results in nothing being built. My changes fix that by leaving off the `--override` option if there aren't any overrides.

Allow omnibus_build resource to not specify config_overrides

---

metadata.rb
recipes/_compile.rb
recipes/_ruby.rb

There's 2 changes here:
First, we need to get the build toolchain into the path. These changes are in `_compile.rb`.
Second, I've removed the devkit mingw from the path because:
> Devkit installs a thing which does this. It runs that whenever
> rubygems needs to gem install something that has native extensions.
> 
> The issue with having this in the path is if you did something like
> install a build toolchain that came before the devkit mingw path.
> In this case, gem installing will not correctly use the devkit toolchain
> because it only checks that Devkit/mingw is in the path, meaning the
> toolchain we put in front of it will be used instead.
This relies on https://github.com/chef-cookbooks/build-essential/pull/80 to function correctly

Setup windows builders to build ruby

---

.kitchen.yml
metadata.rb
recipes/_common.rb
recipes/_compile.rb
recipes/_packaging.rb
recipes/_user.rb

This allows users to run `omnibus::ephemeral` to set up an ephemeral slave whose security they don't care about, without compromising the default recipe, so that test-kitchen runs are easier to do in vagrant (whose password does not pass the default password requirements in a bento box).

Work with test-kitchen and bento boxes

---

.kitchen.docker.yml

There is a bug in the version of Curl (7.38.0) that ships in the Debian 8 Docker image. This version of Curl returns the following error when attempting to download a Chef package from **packages.chef.io**:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```
This does not appear to be an SNI issue as the **chef.bintray.com** version Chef package URL returns the same error. Furthermore Wget downloads the Chef package without issue. Full details on the Curl bug at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814070
The easiest workaround is to ensure Wget is installed before attempting to install Chef as `install.sh` will use `curl` or `wget` to fetch remote files:
https://git.io/vVO4r

Workaround Curl bug in the Debian 8 Docker image

---

libraries/omnibus_build.rb
spec/libraries/provider_omnibus_build_spec.rb

The backward compatible way to source `load-omnibus-toolchain.sh` is using `.` which is available in `/bin/sh`.
Fixes #141

The `source` command is not available in all shells

---

libraries/helper.rb
metadata.rb
recipes/_compile.rb
spec/libraries/provider_omnibus_build_windows_spec.rb
spec/recipes/compile_spec.rb
spec/spec_helper.rb

The `build-essential` cookbook now installs both a 32-bit and 64-bit compile MinGW toolchain on Windows by default: https://github.com/chef-cookbooks/build-essential/pull/106 This PR updates `load-omnibus-toolchain.bat` to prefer the 32-bit toolchain on nodes that are identified as 32-bit.
/cc @chef-cookbooks/engineering-services @ksubrama @tyler-ball

Support true 32-bit Windows build toolchain

---

attributes/default.rb

/cc: @chef-cookbooks/engineering-services 
This is preparing to get Ruby 2.1.8 that is included in omnibus-toolchain 1.1.7 into our slaves.

Bump the version of omnibus-toolchain to 1.1.7

---

attributes/default.rb

This should fix licensing download errors on jenkins chef builders. On ruby 2.1.5 (the current ruby default version) the following code:
```
require 'open-uri'
open("https://www.openssl.org/source/license.html")
```
produces an error:
```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
```
Ruby 2.1.8 is able to successfully download the license.

default to ruby version 2.1.8

---

recipes/_omnibus_toolchain.rb

Use platform_version_compatibility_mode to get the toolchain package that was built and tested for the latest version of a supported platform if the specified version of that platform is not present in our official support matrix.
cc @chef-cookbooks/engineering-services

[JEX-169] Use platform_version_compatibility_mode to install toolchain on ubuntu 16.04

---

recipes/_packaging.rb

@chef-cookbooks/omnibus-maintainers 
Tested on debian and ubuntu

Add fakeroot back to only debian style

---

attributes/default.rb
libraries/helper.rb
recipes/_environment.rb
recipes/_git.rb
spec/recipes/git_spec.rb
spec/recipes/user_spec.rb
test/fixtures/cookbooks/omnibus_build/recipes/execute.rb
test/integration/default/serverspec/default_spec.rb

This bumps the toolchain to version 1.1.10, which includes git/ruby version bumps and removes fakeroot.
@chef-cookbooks/omnibus-maintainers 

Update toolchain version

---

attributes/default.rb

First release of angry-omnibus-toolchain that includes s390x packages, required to bootstrap the omnibus-toolchain build nodes.

Update toolchain version to include packages for s390x

---

attributes/default.rb

This is the first version that contains the full s390x matrix for both angry and regular toolchain.

Update omnibus-toolchain to version 1.1.42.

---

recipes/_user.rb

Avoids managing build user group on Windows.  Since the block that creates the group is set to `ignore_failure true`, there is no reason to try and operate on build group for Windows platform, since it will most likely fail to create the group on Windows.
Signed-off-by: Eric G. Wolfe <eric.wolfe@gmail.com>

Windows has no build user group

---

README.md
libraries/omnibus_build.rb
spec/libraries/provider_omnibus_build_spec.rb
spec/libraries/provider_omnibus_build_windows_spec.rb

This change adds support for toggling the `live_stream` property of execute resources generated by `omnibus_build` resources.
No existing issue for this feature.
Without this feature we were unable to use Omnibus to build Sensu via Travis, due to lack of output from the build. Enabling `live_stream` on our Omnibus build execution resources gives us enough live output that Travis allows our build to continue.

add live_stream attribute to OmnibusBuild provider

---

.travis.yml
libraries/helper.rb

This PR the `windows_safe_path_join` helper method which would raise an exception when `File::ALT_SEPARATOR` returned `nil`

Make `windows_safe_path_join` helper safe on non-windows platforms

---

CHANGELOG.md
metadata.rb

Prepare 5.1.1 release.
- Make `windows_safe_path_join` smarter and allow strings or arrays as input.
- Fix travis failures due to unsupported metadata.
/cc @chef-cookbooks/omnibus-maintainers 

Release v5.1.1

---

.travis.yml
metadata.rb
recipes/_omnibus_toolchain.rb
spec/spec_helper.rb

This change will require https://github.com/chef-cookbooks/chef-ingredient/pull/128 being merged and released and removal of 0ccc287.

Use new `architecture` attribute on toolchain install

---

recipes/_omnibus_toolchain.rb

This explicitly overrides suse 11 and 12 to use the RHEL 5 and 6 toolchains for compatibility.

Force an override of the toolchain platform on suse

---

.delivery/build-cookbook/metadata.rb
Berksfile

Modern chef includes this functionality
Signed-off-by: Tim Smith <tsmith@chef.io>

Remove fancy_execute cookbook

---

recipes/_environment.rb

this is actually critically necessary for BUNDLER_VERSION
which collides horribly with the env var of the same name
in bundler 1.14.x which is used for bundler trampolining into
a specific version of bundler.
the value that this script is setting BUNDLER_VERSION to
is nonsensical for the new bundler code so it always errors
out, and consumers wouldn't want to be forced to be trampolined
back into the external bundler version all the time anyway.

prefix all windows vars by OMNIBUS_

---

.travis.yml
attributes/default.rb
spec/libraries/provider_omnibus_build_spec.rb

This pulls in the latest GCC for windows which is required as the previous toolchain had a GCC version that had some bugs that were preventing chefdk from building
@chef-cookbooks/engineering-services @chef-cookbooks/omnibus-maintainers 

Bump omnibus toolchain version. 

---

libraries/omnibus_build.rb
spec/libraries/provider_omnibus_build_spec.rb

In Chef Client 13 some types of resource properties became immutable, including Hash.
So, in order to change the "environment" hash, we need to create a mutable copy first.
Fixes #213

omnibus_build: Duplicate an immutable property

---

recipes/_packaging.rb
spec/recipes/packaging_spec.rb

This commit adds two new packages to be installed on Debian (and its derivatives e.g. Ubuntu) which are needed by Omnibus to sign the newly built packages. The newly added packages are `binutils` (to supply the GNU `ar` binary) and `gnupg` to ensure that GnuPG is installed.
https://github.com/chef/omnibus/issues/402
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>

Add packages needed for Debian (deb) packages signing.

---

metadata.rb
recipes/_packaging.rb

This is due to what appears to be a bug in the actual sdk setup executable.
When installing from a dos path (anything that has > 8 characters in the name),
the installer will truncate the download URL for some unknown reason, turning
<base_url>/Patches/<name> into <base_url>/hes/<name>. I have no idea what is
causing this but this code essentially forces a powershell invocation in the
current directory, which by default uses the correct "Long File" format.

Update Windows SDK installation method.

---

recipes/_environment.rb

freeware should be searched last else compile fails
Update AIX PATH to include updated compiler and search freeware last

Fix AIX env PATH

---

libraries/omnibus_build.rb
recipes/_compile.rb

In commit ca4e42910a77c, the arguments to `File.join` were changed
from two arguments using the return from `build_user_home` and the
`load-omnnibus-toolchain.sh` file to using the return from
`build_user_home` sending an argument `load-omnibus-toolchain.sh`.
This causes an ArgumentError exception to be raised when attempting to
use the `omnibus_build` resource in an existing cookbook because
`build_user_home`'s method signature takes no arguments.
It's unclear whether the cookstyle of January 2019 caused an error on
this particular line of code, but I ran cookstyle 5.20.0 from Chef
Workstation 0.16.5 (latest stable release as of today) against this
change and it was not a finding. It did find an issue with the use of
`node.normal` in the `_compile.rb` recipe, so I fixed that unrelated …

undo a change from previous cookstyle, and cookstyle
